version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: ./src
      dockerfile: Dockerfile.app
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_QUEUES_TOTAL: 10
      CELERY_QUEUES_PER_SET: 5
    image: jrhuerta/celery-demo:app
    ports:
      - "5000:5000"
    volumes:
      - "./src:/app"
  worker:
    build:
      context: ./src
      dockerfile: Dockerfile.worker
    image: jrhuerta/celery-demo:worker
#    volumes:
#      - "./src:/app"
  monitor:
    build:
      context: ./src
      dockerfile: Dockerfile.monitor
    image: jrhuerta/celery-demo:monitor
    environment:
      CELERY_MONITOR_QUEUES: "queue1001,queue1002,queue1003"
    command: ["python", "monitor.py", "-d"]
    ports:
      - "9540:9540"
    volumes:
    - "./src:/app"

